version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis:Z

  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm

  gitlab:
    restart: always
    image: sameersbn/gitlab:8.16.3
    depends_on:
    - redis
    - postgresql
    ports:
    - "22:22"
    volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data:Z
    - /srv/docker/gitlab/gitlab/logs:/var/log/gitlab:Z
    environment:
    - DEBUG=true

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - TZ=Asia/Kolkata
    - GITLAB_TIMEZONE=Kolkata

    - GITLAB_HTTPS=true
    - SSL_SELF_SIGNED=true

    - GITLAB_HOST=CHANGEME
    - GITLAB_SSH_PORT=22
    - GITLAB_RELATIVE_URL_ROOT=
    - GITLAB_SECRETS_DB_KEY_BASE=CHANGEME
    - GITLAB_SECRETS_SECRET_KEY_BASE=CHANGEME
    - GITLAB_SECRETS_OTP_KEY_BASE=CHENGEME

    - GITLAB_ROOT_PASSWORD=
    - GITLAB_ROOT_EMAIL=

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=changeme@mail.com
    - GITLAB_EMAIL_REPLY_TO=noreply@mail.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=lab@mail.com

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=true
    - SMTP_DOMAIN=changeme.com
    - SMTP_HOST=mail.changeme.com
    - SMTP_PORT=587
    - SMTP_USER=changeme
    - SMTP_PASS=changeme
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=plain

    - IMAP_ENABLED=true
    - IMAP_HOST=mail.changeme.com
    - IMAP_PORT=993
    - IMAP_USER=change@me.com
    - IMAP_PASS=changeme
    - IMAP_SSL=true
    - IMAP_STARTTLS=false

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - gitlab:gitlab
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl

